spring:
  profiles:
    active: dev

coolsms:
  api:
    key: NCSCANIL8J8QIMTQ
    secret: QKBYHKEBOUHCY4IX1SLQOUNKNPKOVBLC
    fromNum: 01051416922

jwt :
  expiration-time : 86400
  secret : ohmygodthisisjson





