server:
  port: 8080

spring :
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000

  datasource:
    url: jdbc:mariadb://database-2.crqs42o0eh7q.us-east-1.rds.amazonaws.com:3306/knock
    username: admin
    password: knockknock
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql


